### ISSUE TITLE
JS Test Cases

### ISSUE THREAD

**Issue by HarshBathija** [aditya4196/SimplyClip#12]

**Comment by HarshBathija** [comment]
I have done the Dark mode test case

**Comment by HarshBathija** [comment]
I have done the selecting checkboxes and Merging Functionality test case

**Comment by HarshBathija** [comment]
I completed the sorting functionality

**Comment by HarshBathija** [comment]
@aditya4196 Please verify

**Comment by aditya4196** [comment]
verified the tests on chrome browser
