### ISSUE TITLE
Dark Mode Functionality

### ISSUE THREAD

**Issue by abhi031098** [aditya4196/SimplyClip#2]
Create a dark mode functionality in the clipboard

**Comment by HarshBathija** [comment]
I have completed this functionality. @aditya4196 please verify

**Comment by HarshBathija** [comment]
I have also stored the 'enable' button to local storage

**Comment by abhi031098** [comment]
The previously completed code by me for dark functionality works properly in the project since the current ones have a few issues like text being unreadable in certain instances. @aditya4196 can you verify the same and revert back to the previous commits for dark functionality?

**Comment by aditya4196** [comment]
I will verify it with harsh and update you with the status.

**Comment by aditya4196** [comment]
I verified it with harsh and it is working fine. Hence, no need to revert it back.

**Comment by abhi031098** [comment]
The issue is in hover functionality

**Comment by abhi031098** [comment]
It's working fine
